#!/usr/bin/env node
// bmad-generated:7c4683b9
// BMAD Swarm - Stop Hook for Delegation Verification
// Generated by bmad-swarm - do not edit manually
//
// Fires when Claude is about to stop/respond.
// Checks if the orchestrator modified code files directly during this turn.
// If violations are detected, blocks the turn so the orchestrator must revert.

const fs = require('fs');
const path = require('path');

const CODE_DIR = "./src";

let input = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => { input += chunk; });
process.stdin.on('end', () => {
  const cwd = process.cwd();
  const markerPath = path.join(cwd, '.claude', 'hooks', '.code-modified-marker');

  let marker = null;
  try {
    const raw = fs.readFileSync(markerPath, 'utf8');
    marker = JSON.parse(raw);
  } catch {
    // No marker file = no violations
    process.exit(0);
  }

  // Check if the marker is recent (within the last 10 minutes)
  const age = Date.now() - (marker.timestamp || 0);
  if (age > 10 * 60 * 1000) {
    // Stale marker, clean up and pass
    try { fs.unlinkSync(markerPath); } catch {}
    process.exit(0);
  }

  // Violation detected - clean up marker and block
  try { fs.unlinkSync(markerPath); } catch {}

  const output = JSON.stringify({
    decision: 'block',
    reason: 'You implemented code in ' + CODE_DIR + ' directly instead of delegating to a developer agent. Revert your changes and delegate the implementation work to a developer agent.',
  });
  process.stdout.write(output);
  process.exit(0);
});
