#!/usr/bin/env node
// BMAD Swarm - TaskCompleted Hook
// Generated by bmad-swarm - do not edit manually

const { execSync } = require('child_process');

const taskId = process.env.TASK_ID || '';
const taskSubject = process.env.TASK_SUBJECT || '';
const taskOwner = process.env.TASK_OWNER || '';

console.log(`[BMAD Swarm] Task completed: ${taskSubject} (by ${taskOwner})`);

const isImplementation = taskSubject.includes('implement') || taskSubject.includes('develop') || taskSubject.includes('dev-');

if (isImplementation) {
  try {
    execSync('npm test', { stdio: 'pipe', timeout: 60000 });
    console.log('[BMAD Swarm] \u2713 Tests passed');
  } catch (err) {
    console.log('[BMAD Swarm] \u2717 Tests failed');
    if (err.stdout) console.log(err.stdout.toString().slice(-500));
    console.log('[BMAD Swarm] Advisory: Fix failing tests before merging');
  }
}

process.exit(0);
