#!/bin/bash
# BMAD Swarm - TaskCompleted Hook
# Generated by bmad-swarm - do not edit manually
# This hook runs when an agent marks a task as complete.
# It validates quality gate criteria before accepting the completion.

# The task details are passed via environment variables:
# TASK_ID - The completed task ID
# TASK_SUBJECT - The task subject
# TASK_OWNER - The agent that completed the task

ARTIFACTS_DIR="./artifacts"

# Log task completion
echo "[BMAD Swarm] Task completed: $TASK_SUBJECT (by $TASK_OWNER)"

# Quality gate checks

# Check: Tests should exist if implementation task
if [[ "$TASK_SUBJECT" == *"implement"* ]] || [[ "$TASK_SUBJECT" == *"develop"* ]] || [[ "$TASK_SUBJECT" == *"dev-"* ]]; then
  echo "[BMAD Swarm] Implementation task - tests will be validated during review"
fi



# Check: Flag for review requirement
if [[ "$TASK_SUBJECT" == *"implement"* ]] || [[ "$TASK_SUBJECT" == *"develop"* ]] || [[ "$TASK_SUBJECT" == *"dev-"* ]]; then
  echo "[BMAD Swarm] Note: This task requires code review before the story is considered done"
fi


exit 0
