#!/usr/bin/env node
// bmad-generated:6be77637
// BMAD Swarm - PreToolUse gate on TeamCreate
// Generated by bmad-swarm - do not edit manually
//
// Reads the recent transcript and requires a fenced bmad-assembly block
// with required keys to have been emitted by the most recent assistant
// message before TeamCreate is allowed. Blocks with permissionDecision
// 'deny' otherwise. If no transcript is available the hook fails open.

const fs = require('fs');
const path = require('path');
let input = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (c) => { input += c; });
process.stdin.on('end', () => {
  let event;
  try { event = JSON.parse(input); } catch { process.exit(0); }
  const transcriptPath = event.transcript_path;
  if (!transcriptPath || !fs.existsSync(transcriptPath)) { process.exit(0); }
  let content;
  try { content = fs.readFileSync(transcriptPath, 'utf8'); } catch { process.exit(0); }
  const blockPattern = /\`\`\`bmad-assembly\n([\s\S]*?)\n\`\`\`/g;
  const matches = [...content.matchAll(blockPattern)];
  const lastBlock = matches.length ? matches[matches.length - 1][1] : null;
  const REQUIRED_KEYS = ['entry_point', 'complexity', 'autonomy', 'team', 'rationale'];
  function missingKeys(block) {
    if (!block) return REQUIRED_KEYS;
    return REQUIRED_KEYS.filter(k => !new RegExp('^' + k + ':', 'm').test(block));
  }
  const missing = missingKeys(lastBlock);
  if (missing.length > 0) {
    process.stdout.write(JSON.stringify({
      hookSpecificOutput: {
        hookEventName: 'PreToolUse',
        permissionDecision: 'deny',
        permissionDecisionReason: 'Blocked: produce a bmad-assembly block (with keys: ' + REQUIRED_KEYS.join(', ') + ') in your message BEFORE calling TeamCreate. Missing: ' + missing.join(', '),
      },
    }));
    process.exit(0);
  }
  process.exit(0);
});
