#!/bin/bash
# BMAD Swarm - TeammateIdle Hook
# Generated by bmad-swarm - do not edit manually
# This hook runs when a teammate goes idle.

# TEAMMATE_NAME - Name of the idle teammate
# TEAMMATE_ID - Agent ID of the idle teammate

echo "[BMAD Swarm] Teammate idle: $TEAMMATE_NAME"

exit 0
