#!/usr/bin/env node
// bmad-generated:035d3a4b
// BMAD Swarm - PreToolUse gate on TeamCreate
// Generated by bmad-swarm - do not edit manually
//
// Parses the JSONL transcript and requires a fenced bmad-assembly block with
// the required keys to appear in the last N=5 assistant message.ids. Accepts
// both 'text' and 'thinking' content blocks. Widening the search from the
// single last message.id to the last 5 message.ids covers streaming splits,
// retries after transient failures, and the common 'plan in message → tool_use
// in next message' pattern. Fails open when the transcript is missing or
// unreadable. This is a shape check, not an authorization boundary.
//
// GATE-1 (2.0.2): raw-transcript-scan fallback. When the structured content-
// block walk does not surface the fence — observed when an assistant message
// starts with only a fenced bmad-assembly block and the transcript JSON
// encodes the content in a shape the typed walk misses — a secondary pass
// scans the raw transcript text for the fence. Both passes enforce the same
// 5-key requirement; only denies if NEITHER finds a valid block.
//
// Pass 2 (ADR-008, D-009): fixed-mode routing enforcement. After Pass 1
// accepts the bmad-assembly envelope shape, Pass 2 reads swarm.yaml from
// CWD. When team.mode === 'fixed', it validates each team[].entry against
// team.specializations: specialized roles (developer, reviewer) with a
// matching (role, domain) pair pass; without a domain, fall back to
// team.fallback (when enabled and role matches); unspecialized roles pass
// unconditionally. Fail-open posture: missing/malformed swarm.yaml or any
// js-yaml require/parse failure skips Pass 2 silently (D-012). Routing
// failures are correctness issues, not security issues — the reviewer is
// the backstop. Dynamic mode (or absent team block) sees zero behavior
// change.

const fs = require('fs');
const path = require('path');
let input = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (c) => { input += c; });
process.stdin.on('end', () => {
  let event;
  try { event = JSON.parse(input); } catch { process.exit(0); }
  const transcriptPath = event.transcript_path;
  if (!transcriptPath || !fs.existsSync(transcriptPath)) { process.exit(0); }
  let raw;
  try { raw = fs.readFileSync(transcriptPath, 'utf8'); } catch { process.exit(0); }

  const entries = raw.split(/\r?\n/).filter(Boolean)
    .map(l => { try { return JSON.parse(l); } catch { return null; } })
    .filter(e => e && e.type === 'assistant' && e.message);
  const REQUIRED_KEYS = ['entry_point', 'complexity', 'autonomy', 'team', 'rationale'];
  const FENCE_RE = /```bmad-assembly\s*\n([\s\S]*?)\n```/;
  function denyMissing(missing) {
    process.stdout.write(JSON.stringify({
      hookSpecificOutput: {
        hookEventName: 'PreToolUse',
        permissionDecision: 'deny',
        permissionDecisionReason: 'Blocked: produce a bmad-assembly block (with keys: ' + REQUIRED_KEYS.join(', ') + ') in your message BEFORE calling TeamCreate. Missing: ' + missing.join(', '),
      },
    }));
  }
  function denyRouting(reason) {
    process.stdout.write(JSON.stringify({
      hookSpecificOutput: {
        hookEventName: 'PreToolUse',
        permissionDecision: 'deny',
        permissionDecisionReason: reason,
      },
    }));
  }
  function missingKeys(block) {
    if (!block) return REQUIRED_KEYS.slice();
    return REQUIRED_KEYS.filter(k => !new RegExp('^\\s*' + k + ':', 'm').test(block));
  }
  if (entries.length === 0) { denyMissing(REQUIRED_KEYS); process.exit(0); }

  // Pass 1: structured content-block walk over last N=5 distinct assistant
  // message.ids, accepting both 'text' and 'thinking' blocks.
  const N = 5;
  const recentIds = new Set();
  for (let i = entries.length - 1; i >= 0 && recentIds.size < N; i--) {
    recentIds.add(entries[i].message.id);
  }
  const texts = [];
  for (const e of entries) {
    if (!recentIds.has(e.message.id)) continue;
    const content = Array.isArray(e.message.content) ? e.message.content : [];
    for (const b of content) {
      if (!b) continue;
      if (b.type === 'text' && b.text) texts.push(b.text);
      else if (b.type === 'thinking' && b.thinking) texts.push(b.thinking);
    }
  }
  const structuredText = texts.join('\n');
  const structuredMatch = structuredText.match(FENCE_RE);
  const structuredMissing = missingKeys(structuredMatch ? structuredMatch[1] : null);
  let acceptedBlock = null;
  if (structuredMissing.length === 0) {
    acceptedBlock = structuredMatch[1];
  } else {
    // Pass 1 fallback: raw-transcript-scan. GATE-1 observed that some message
    // shapes don't surface the fence through the typed-block walk; scanning the
    // raw JSON directly catches those. Scope the raw scan to only the raw JSONL
    // lines whose parsed assistant entries belong to the same recent N message
    // ids the structured walk used — preserves the "plan BEFORE create"
    // recency invariant while recovering from walk-misses. The raw JSONL
    // encodes real newlines as the two-char sequence \n so we un-escape those
    // before matching so a fence that exists only inside a JSON-stringified
    // value still triggers a pass. Also cap the scanned region at ~50KB as a
    // belt-and-braces guard against pathological transcripts.
    const RAW_TAIL_BYTES = 50 * 1024;
    const rawLines = raw.split(/\r?\n/);
    const recentRawLines = [];
    for (const line of rawLines) {
      if (!line) continue;
      let parsed;
      try { parsed = JSON.parse(line); } catch { continue; }
      if (parsed && parsed.type === 'assistant' && parsed.message && recentIds.has(parsed.message.id)) {
        recentRawLines.push(line);
      }
    }
    let rawScope = recentRawLines.join('\n');
    if (rawScope.length > RAW_TAIL_BYTES) {
      rawScope = rawScope.slice(rawScope.length - RAW_TAIL_BYTES);
    }
    const rawUnescaped = rawScope.replace(/\\n/g, '\n');
    const rawMatch = rawUnescaped.match(FENCE_RE);
    if (rawMatch) {
      const rawMissing = missingKeys(rawMatch[1]);
      if (rawMissing.length === 0) {
        acceptedBlock = rawMatch[1];
      }
    }
  }

  if (acceptedBlock === null) {
    denyMissing(structuredMissing);
    process.exit(0);
  }

  // Pass 2 (ADR-008): fixed-mode routing enforcement. Fail-open on every
  // error path — missing swarm.yaml, missing js-yaml dep, parse error, or
  // unexpected shape. Pass 2 runs ONLY after Pass 1 has accepted.
  let yaml;
  try { yaml = require('js-yaml'); } catch { process.exit(0); }

  const swarmYamlPath = path.join(process.cwd(), 'swarm.yaml');
  if (!fs.existsSync(swarmYamlPath)) { process.exit(0); }
  let swarmRaw;
  try { swarmRaw = fs.readFileSync(swarmYamlPath, 'utf8'); } catch { process.exit(0); }
  let swarmConfig;
  try { swarmConfig = yaml.load(swarmRaw); } catch { process.exit(0); }
  if (!swarmConfig || typeof swarmConfig !== 'object') { process.exit(0); }

  const teamCfg = swarmConfig.team || {};
  const mode = teamCfg.mode || 'dynamic';
  if (mode !== 'fixed') { process.exit(0); }

  const specs = Array.isArray(teamCfg.specializations) ? teamCfg.specializations : [];
  const fallback = teamCfg.fallback || {};
  // Match utils/config.js defaults: enabled defaults to true, role defaults
  // to 'developer'. The hook duplicates this default-application logic
  // intentionally — it does not import from utils/config.js to keep the
  // hook a self-contained CommonJS script (D-012).
  const fallbackEnabled = fallback.enabled !== false;
  const fallbackRole = fallback.role || 'developer';

  const SPECIALIZED_ROLES = new Set(['developer', 'reviewer']);

  let assembly;
  try { assembly = yaml.load(acceptedBlock); } catch { process.exit(0); }
  if (!assembly || typeof assembly !== 'object') { process.exit(0); }
  const teamArray = Array.isArray(assembly.team) ? assembly.team : [];

  for (const entry of teamArray) {
    if (!entry || typeof entry !== 'object') continue;
    const role = entry.role;
    if (!role || !SPECIALIZED_ROLES.has(role)) continue;

    const domain = entry.domain;
    if (domain) {
      const matched = specs.some(s => s && s.role === role && s.domain === domain);
      if (!matched) {
        denyRouting('Blocked: team mode is "fixed" but the team[] entry "' + role + ' domain=' + domain + '" does not match any declared specialist in swarm.yaml:team.specializations and fallback is disabled. Either declare the specialist or set team.fallback.enabled: true.');
        process.exit(0);
      }
    } else {
      if (!(fallbackEnabled && fallbackRole === role)) {
        denyRouting('Blocked: team mode is "fixed" but the team[] entry "' + role + '" (no domain) does not match any declared specialist in swarm.yaml:team.specializations and fallback is disabled. Either declare the specialist or set team.fallback.enabled: true.');
        process.exit(0);
      }
    }
  }

  process.exit(0);
});
