#!/usr/bin/env node
// bmad-generated:5eaaf7e3
// BMAD Swarm - TeammateIdle Hook
// Generated by bmad-swarm - do not edit manually

const teammateName = process.env.TEAMMATE_NAME || '';
const teammateId = process.env.TEAMMATE_ID || '';

console.log(`[BMAD Swarm] Teammate idle: ${teammateName}`);

if (teammateName.includes('orchestrator')) {
  console.log('[BMAD Swarm] Warning: Orchestrator is idle - check if tasks are pending');
}

process.exit(0);
