/**
 * GitHub integration utilities for bmad-swarm.
 * Provides helpers for orchestrator agents to interact with GitHub.
 */

/**
 * Generate PR description from completed stories.
 * @param {object} options - { title, stories, artifacts }
 * @returns {string} Markdown PR body
 */
export function generatePRDescription(options) {
  const { title, stories = [], artifacts = [] } = options;
  let body = `## Summary\n\n${title}\n\n`;

  if (stories.length > 0) {
    body += '## Stories Implemented\n\n';
    for (const story of stories) {
      body += `- ${story}\n`;
    }
    body += '\n';
  }

  if (artifacts.length > 0) {
    body += '## Artifacts\n\n';
    for (const artifact of artifacts) {
      body += `- \`${artifact}\`\n`;
    }
    body += '\n';
  }

  body += '---\n*Generated by BMAD Swarm*\n';
  return body;
}

/**
 * Generate issue body from QA findings.
 * @param {object} finding - { title, description, severity, foundBy }
 * @returns {string} Markdown issue body
 */
export function generateIssueBody(finding) {
  return `## ${finding.title}

**Severity**: ${finding.severity || 'medium'}
**Found by**: ${finding.foundBy || 'QA Agent'}

### Description

${finding.description}

---
*Created by BMAD Swarm QA*
`;
}
