# BMAD Swarm - Project State
# This file tracks the current state of the project build

project:
  name: "@bmad/swarm"
  description: "Autonomous development swarm powered by Claude Code Agent Teams"
  type: npm-package
  repo: BMAD-Teams

stack:
  language: javascript
  runtime: node >= 18
  module_system: esm
  test_framework: "node:test"
  dependencies:
    - commander
    - js-yaml

phase: implementation
autonomy: guided

design_spec: artifacts/design/v1-system-design.md
inspiration_source: _bmad/

deliverables:
  - name: CLI tool
    description: "bmad-swarm command with init, update, eject, uneject, scan, status subcommands"
    status: not-started

  - name: Agent templates
    description: "8 agent definition templates (orchestrator, researcher, strategist, architect, story-engineer, developer, reviewer, qa)"
    status: not-started

  - name: Methodology content
    description: "Phase definitions, task graph templates, quality gates, artifact schemas"
    status: not-started

  - name: Config system
    description: "swarm.yaml schema, layering logic, eject/uneject mechanism"
    status: not-started

  - name: Generators
    description: "Code that merges agent templates + project config to produce .claude/agents/ files"
    status: not-started

  - name: Project templates
    description: "Default swarm.yaml, CLAUDE.md template, settings.json template"
    status: not-started

  - name: Tests
    description: "CLI tests, generator tests, template validation"
    status: not-started

decisions:
  - date: 2026-02-09
    decision: "Use Node.js with ES modules, minimal dependencies"
    rationale: "Keep the package lightweight and easy to install globally"

  - date: 2026-02-09
    decision: "Agent definitions are markdown files in .claude/agents/"
    rationale: "This is Claude Code's native format for custom teammate definitions"

  - date: 2026-02-09
    decision: "Config via YAML (swarm.yaml) with layered override system"
    rationale: "YAML is human-readable, the layering pattern (package → config → eject) prevents copy-paste"
